name: Release changes to production

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/strapi:latest
          outputs: type=docker,dest=/tmp/${{ secrets.DOCKER_USERNAME }}-strapi.tar

      - name: Deploy app
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /tmp/${{ secrets.DOCKER_USERNAME }}-strapi.tar
          remote: ${{ secrets.REMOTE_SERVER_FOLDER }}
          host: ${{ secrets.REMOTE_SERVER_IP }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
