name: Release changes to production

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/strapi:latest
          outputs: type=docker,dest=strapi.tar

#      - name: Deploy app
#        uses: garygrossgarten/github-action-scp@release
#        with:
#          local: strapi.tar
#          remote: ${{ secrets.REMOTE_SERVER_FOLDER }}
#          host: ${{ secrets.REMOTE_SERVER_IP }}
#          port: ${{ secrets.REMOTE_SERVER_PORT }}
#          username: ${{ secrets.REMOTE_SERVER_USER }}
#          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
#          rmRemote: true

      - name: Deploy app
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './strapi.tar'
          remote: '/home/${{ secrets.REMOTE_SERVER_USER }}'
          host: ${{ secrets.REMOTE_SERVER_IP }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          user: ${{ secrets.REMOTE_SERVER_USER }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}

      - name: Rerun application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          script: |
            docker load --input ${{ secrets.REMOTE_SERVER_FOLDER }}/strapi.tar
            docker-compose up
